#!/usr/bin/env python3

import colors as c

import random 
print("""
Welcome To The Magic 8 ball
Enter your question below:
""")

answers =  [
c.b + "Yes." + c.x,
c.r + "No." + c.x,
c.m + "Maybe." + c.x,
c.g + "Defintly." + c.x,
c.b + "I Dont Think so."+ c.x,
c.m + "when pigs fly." + c.x,
c.o + "in 20000 years." + c.x,
c.base03 + "when you become Vader." + c.x,
c.r + "who cares." + c.x,
c.m + "when you die." + c.x,
c.o + "Good." + c.x,
c.g + "duh." + c.x,
'''           
HHHHHHH       HHHHHHH  E 
H:::::H       H:::::H  E
H:::::H       H:::::H
H:::::H       H:::::H
h:::::H       H:::::H
H:::::HHHHHHHHH:::::H
H:::::::::::::::::::H
H:::::::::::::::::::H
H:::::::::::::::::::H
H:::::::::::::::::::H
H:::::HHHHHHHHH:::::H
H:::::H       H:::::H
H:::::H       H:::::H
H:::::H       H:::::H
H:::::H       H:::::H
HHHHHHH       HHHHHHH  
''',

"""



                             OOOOOOOO     
N:::::::N       N::::::N   OO:::::::::OO   
N::::::::N      N::::::N OO:::::::::::::OO 
N:::::::::N     N::::::NO:::::::OOO:::::::O
N::::::::::N    N::::::NO::::::O   O::::::O
N:::::::::::N   N::::::NO:::::O     O:::::O
N:::::::N::::N  N::::::NO:::::O     O:::::O
N::::::N N::::N N::::::NO:::::O     O:::::O
N::::::N  N::::N:::::::NO:::::O     O:::::O
N::::::N   N:::::::::::NO:::::O     O:::::O
N::::::N    N::::::::::NO:::::O     O:::::O
N::::::N     N:::::::::NO::::::O   O::::::O
N::::::N      N::::::::NO:::::::OOO:::::::O
N::::::N       N:::::::N OO:::::::::::::OO 
N::::::N        N::::::N   OO:::::::::OO   
NNNNNNNN         NNNNNNN     OOOOOOOOO     
    """

]

def ask(prompt):
    answer = input("-->").strip().lower()
    return answer

def bye():
    print("bye bye come back in 2 seconds!")
    exit()

try:


    while True:
        question = ask("-->")
        if "die" in question or  "death" in question:
            print(c.base3 +  "Well that is very morbid" + c.x)
        elif "love" in question:
            print(c.red + "love is beyond my powers to predict." + c.x)
        elif "bye"  in question or "goodbye" in question:
            bye()
        else:
            answer = random.choice(answers)
            print(answer)

except KeyboardInterrupt:
    bye()
